import { Job } from "./types";
import jobsData from "./jobs-data.json";

// Generated by scripts/scrape-jobs.mjs (run `npm run scrape-jobs` to refresh).
// Do not hand-edit this list - it gets fully replaced on the next scrape.
export const jobs: Job[] = jobsData as Job[];
